### PR TITLE
updated dependencies

### PR DESCRIPTION
**Pull request by Chaitanya-087**

### CODE REVIEW

**Comment by jalaj711** [comment]
Hi, @Chaitanya-087

Thank you for the PR. The updates seem to have broken the build and I am getting the following error on doing `npm start`:

#8 broken build

I think this can be resolved by using `Routes` instead of `Switch` in the `app.js` file.
For the `<Redirect>` component error, I believe we will have to use the `withRouter` HOC wrapper and then navigate programmatically. Or to make things even better, you may also convert that class-based component in the file to a function based component and then use the `useNavigate` hook.

You can refer to the documentation here: https://reactrouter.com/en/main/upgrading/v5#upgrade-to-react-router-v6

Kindly resolve the above errors for the PR to be merged. In case you face any difficulty, please feel free to reach out here :).

**Review by j414j — CHANGES_REQUESTED** [review]
Hi, @Chaitanya-087

Thank you for the PR. The updates seem to have broken the build and I am getting the following error on doing `npm start`:

#8 broken build

I think this can be resolved by using `Routes` instead of `Switch` in the `app.js` file.
For the `<Redirect>` component error, I believe we will have to use the `withRouter` HOC wrapper and then navigate programmatically. Or to make things even better, you may also convert that class-based component in the file to a function based component and then use the `useNavigate` hook.

You can refer to the documentation here: https://reactrouter.com/en/main/upgrading/v5#upgrade-to-react-router-v6

Kindly resolve the above errors for the PR to be merged. In case you face any difficulty, please feel free to reach out here :).

**Comment by Chaitanya-087** [comment]
sure

**Comment by Chaitanya-087** [comment]
hi! can you check on this pr

**Review by j414j — APPROVED** [review]
Thank you for your contribution.
I have approved  the PR and will add the appropriate labels with this, but I won't be able to merge it in the `master` branch right now. This is because the versions of the different dependencies seem to be conflicting with each other causing the build to be still broken. However, that would be a task for another day as that is beyond the scope of the issue under consideration (#5). You have resolved the issue you promised, therefore I would add the `hacktoberfest-accepted` label as well.

**Comment by Chaitanya-087** [comment]
thank you so much

**Pull request closed without merging**
